version: '3.7'
services: 
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./app/:/usr/src/app/
    ports: 
      - 8000:8000
    env_file: 
      - ./.env.dev
    depends_on: 
      - db

  db:
    image: postgres:12.0-alpine
    volumes: 
      - learn_django_psqldata:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=learn_django
      - POSTGRES_PASSWORD=learn_django
      - POSTGRES_DB=learn_django_dev

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    volumes:
      - learn_django_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes: 
  learn_django_psqldata:
  learn_django_pgadmin:
